# Generated by Django 5.1.4 on 2024-12-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('FullName', models.CharField(max_length=20)),
                ('Sign', models.CharField(max_length=3)),
            ],
        ),
    ]
