# Generated by Django 5.1.4 on 2025-01-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('fullname', models.CharField(max_length=20)),
                ('sign', models.CharField(max_length=3)),
            ],
        ),
    ]
